# Generated by Django 4.2.7 on 2025-12-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('number_of_passengers', models.IntegerField(default=1)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
            ],
        ),
    ]
